pipeline:
  test:
    image: node:14
    commands:
      - npm ci
      - npm run lint

    # Pipeline level conditions aren't supported yet:
    # https://github.com/woodpecker-ci/woodpecker/issues/283
    when:
      event:
        - pull_request
