pipeline:
  install:
    image: node:14
    commands:
      - npm ci
  lint:
    image: node:14
    commands:
      - npm run lint
  build:
    image: node:14
    commands:
      - npm run build
  test:
    image: node:14
    commands:
      - npm test
when:
  event:
    - pull_request
